AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring API - com.smart::user_manage
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  User_manageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.smart.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/user_manage-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  User_manageApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: User_manageApi
